Persistency in PgSQL plugin

diff --git a/plugins/postgresql/commands b/plugins/postgresql/commands
--- a/plugins/postgresql/commands
+++ b/plugins/postgresql/commands
@@ -26,22 +26,25 @@ case "$1" in
     # Temporarily store it to a file
     echo $DB_PASSWORD > "/tmp/db_pwd_$APP"
     chown git: "/tmp/db_pwd_$APP"
-    # Prepare the container
-    if [[ ! -z $3 ]]; then
-       # Execute SQL statements if specified
-       SQL="$3"
-    else
-       SQL=""
+    # Fork DB image
+    IMAGE=$(docker images | grep "dokku/postgresql " |  awk '{print $3}')
+    if [[ -z $IMAGE ]]; then
+        echo "PostgreSQL image not found... Did you run 'dokku plugins-install' ?"
+        exit 1
     fi
-    ID=$(docker run -d dokku/postgresql /usr/bin/prepare_pgsql.sh $DB_PASSWORD $SQL)
+    # Stupid hack to fork
+    ID=$(docker run -d dokku/postgresql exit 0)
     docker wait $ID > /dev/null
-    ID=$(docker commit $ID)
-    docker tag $ID $DB_IMAGE
-    # Run the container
-    ID=$(docker run -p 5432 -d $DB_IMAGE /usr/bin/start_pgsql.sh)
+    IMAGE=$(docker commit $ID)
+    docker tag $IMAGE $DB_IMAGE
+    # Launch container
+    docker run -v /opt/postgresql -p 5432 -d $DB_IMAGE /usr/bin/start_pgsql.sh $DB_PASSWORD > /dev/null
+    sleep 4
+    # Link to a potential existing app
     dokku pg:link $APP $APP
     echo
     echo "-----> PostgreSQL container created: $DB_IMAGE"
+    sleep 2
     dokku pg:info $APP
     ;;
 
@@ -50,7 +53,7 @@ case "$1" in
     ID=$(docker ps -a | grep "$DB_IMAGE":latest |  awk '{print $1}')
     # Stop the container
     docker stop $ID
-    DB_IMAGE=$(docker images | grep "$DB_IMAGE " |  awk '{print $3}')
+    DB_IMAGE=$(docker images | grep "$DB_IMAGE " |  awk '{print $1}')
     # Remove image
     docker rmi $DB_IMAGE
     echo
@@ -93,12 +96,11 @@ case "$1" in
         URL="DATABASE_URL=postgres://root:$DB_PASSWORD@$IP/db"
         cat "/home/git/$APP/ENV" | grep "$URL" || echo "export $URL" >> "/home/git/$APP/ENV"
         echo
-        echo "-----> App $APP linked to $DB_IMAGE database"
-        echo "       $URL"
+        echo "-----> $APP linked to $DB_IMAGE database"
         rm "/tmp/db_pwd_$APP"
     fi
     ;;
-    
+
   pg:logs)
     DB_IMAGE=pg/$APP
     ID=$(docker ps -a | grep "$DB_IMAGE" |  awk '{print $1}')
@@ -107,11 +109,11 @@ case "$1" in
 
   help)
     cat && cat<<EOF
-    pg:create <app> [sql] Create a PostgreSQL container (optionnaly execute SQL statements)
-    pg:delete <app>       Delete specified PostgreSQL container
-    pg:info <app>         Display database informations
-    pg:link <app> <db>    Link an app to a PostgreSQL database
-    pg:logs <app>         Display last logs from PostgreSQL container
+    pg:create <app>     Create a PostgreSQL container
+    pg:delete <app>     Delete specified PostgreSQL container
+    pg:info <app>       Display database informations
+    pg:link <app> <db>  Link an app to a PostgreSQL database
+    pg:logs <app>       Display last logs from PostgreSQL container
 EOF
     ;;
 
