Removed post-deploy/release hooks and instead integrating it into dokku for now

diff --git a/dokku b/dokku
--- a/dokku
+++ b/dokku
@@ -47,18 +47,17 @@ case "$1" in
     APP="$2"; IMAGE="$3"
     pluginhook pre-deploy $APP $IMAGE
 
-    # kill the app when running
-    if [[ -f "$DOKKU_ROOT/$APP/PORT" ]]; then
-      oldid=$(< "$DOKKU_ROOT/$APP/CONTAINER")
-      docker kill $oldid > /dev/null
-    fi
+    dokku ps:deploy $APP
 
-    # start the app
-    id=$(docker run -d -p 5000 -e PORT=5000 $IMAGE /bin/bash -c "/start web")
-    echo $id > "$DOKKU_ROOT/$APP/CONTAINER"
-    port=$(docker port $id 5000 | sed 's/0.0.0.0://')
-    echo $port > "$DOKKU_ROOT/$APP/PORT"
-    echo "http://$(< "$DOKKU_ROOT/HOSTNAME"):$port" > "$DOKKU_ROOT/$APP/URL"
+    # only use web.1 for now...
+    port=$(docker port $APP.web.1 5000 | sed 's/0.0.0.0://') || true
+    if [[ -n "$port" ]]; then
+      echo $port > "$DOKKU_ROOT/$APP/PORT"
+      echo "http://$(< "$DOKKU_ROOT/HOSTNAME"):$port" > "$DOKKU_ROOT/$APP/URL"
+    else
+      echo " !     Failed to get port from $APP.web.1"
+      exit 1
+    fi
 
     pluginhook post-deploy $APP $port
     ;;
