Move nginx:import-ssl to certs:add

diff --git a/plugins/certs/commands b/plugins/certs/commands
--- a/plugins/certs/commands
+++ b/plugins/certs/commands
@@ -4,6 +4,43 @@ source "$(dirname $0)/../common/functions"
 source "$(dirname $0)/functions"
 
 case "$1" in
+  certs:add)
+    [[ -z $2 ]] && echo "Please specify an app to run the command on" && exit 1
+    verify_app_name "$2"
+    [[ -t 0 ]] && echo "Tar archive containing server.crt and server.key expected on stdin" && exit 1
+    APP="$2"
+
+    TEMP_DIR=$(mktemp -d)
+    cd $TEMP_DIR
+    tar xvf - <&0
+
+    CRT_FILE_SEARCH=$(find . -type f -name "*.crt")
+    CRT_FILE_COUNT=$(printf "%s" "$CRT_FILE_SEARCH" | grep -c '^')
+    if [[ $CRT_FILE_COUNT -lt 1 ]]; then
+      echo "Tar archive is missing .crt file" && exit 1
+    elif [[ $CRT_FILE_COUNT -gt 1 ]]; then
+      echo "Tar archive contains more than one .crt file" && exit 1
+    else
+      CRT_FILE=$CRT_FILE_SEARCH
+    fi
+
+    KEY_FILE_SEARCH=$(find . -type f -name "*.key")
+    KEY_FILE_COUNT=$(printf "%s" "$KEY_FILE_SEARCH" | grep -c '^')
+    if [[ $KEY_FILE_COUNT -lt 1 ]]; then
+      echo "Tar archive is missing .key file" && exit 1
+    elif [[ $KEY_FILE_COUNT -gt 1 ]]; then
+      echo "Tar archive contains more than one .key file" && exit 1
+    else
+      KEY_FILE=$KEY_FILE_SEARCH
+    fi
+
+    mkdir -p "$DOKKU_ROOT/$APP/tls"
+    mv "$CRT_FILE" "$DOKKU_ROOT/$APP/tls/server.crt"
+    mv "$KEY_FILE" "$DOKKU_ROOT/$APP/tls/server.key"
+    cd $DOKKU_ROOT
+    rm -rf $TEMP_DIR
+    dokku nginx:build-config $APP
+    ;;
   certs:generate)
     [[ -z $2 ]] && echo "Please specify an app to run the command on" && exit 1
     verify_app_name "$2"
@@ -91,6 +128,7 @@ case "$1" in
 
   help | certs:help)
     cat && cat<<EOF
+    certs:add <app>, Add an ssl endpoint to an app. Imports a tarball from stdin; should contain server.crt and server.key
     certs:generate <app> DOMAIN, Generate a key and certificate signing request (and self-signed certificate)
     certs:info <app>, Show certificate information for an ssl endpoint.
     certs:remove <app>, Remove an SSL Endpoint from an app.
