first pass at fixing deployment tests

diff --git a/tests/test_deploy b/tests/test_deploy
--- a/tests/test_deploy
+++ b/tests/test_deploy
@@ -1,11 +1,21 @@
 #!/usr/bin/env bash
 set -exo pipefail
+
 SELF=`which $0`; APP="$1"; TARGET="$2"; FORWARDED_PORT="$3"
 REMOTE="dokku@$TARGET"
 REPO="test-$(basename $APP)-$RANDOM"
 
+destroy_app(){
+  echo $REPO | ssh $REMOTE apps:destroy $REPO
+}
+
+failed(){
+  echo "************ $1 failed ************"
+  # destroy_app
+  exit 1
+}
+
 TMP=$(mktemp -d -t "$TARGET.XXXXX")
-trap "rm -rf $TMP" EXIT
 rmdir $TMP && cp -r $(dirname $SELF)/$APP $TMP
 cd $TMP
 git init
@@ -19,13 +29,15 @@ git add .
 [[ -x pre-commit ]] && ./pre-commit $REMOTE $REPO
 git commit -m 'initial commit'
 git push target master
-[[ -x post-deploy ]] && ./post-deploy $REMOTE $REPO
+if [[ -x post-deploy ]]; then
+  ./post-deploy $REMOTE $REPO || failed post-deploy
+fi
 
 URL=$(ssh $REMOTE url $REPO)$FORWARDED_PORT
-sleep 2
+sleep 10
 ./check_deploy $URL && echo "-----> Deploy success!" || {
-  sleep 4
-  ./check_deploy $URL && echo "-----> Deploy success!"
+  sleep 30
+  ./check_deploy $URL && echo "-----> Deploy success!" || failed check-deploy
 }
 
-ssh $REMOTE delete $REPO
+destroy_app
