feat: add support for cloning/syncing from a remote repository
This makes it a bit easier for external projects to implement deploy webhooks by exposing the ability to sync from a git repository/sha.

diff --git a/plugins/git/internal-functions b/plugins/git/internal-functions
--- a/plugins/git/internal-functions
+++ b/plugins/git/internal-functions
@@ -4,6 +4,102 @@ source "$PLUGIN_CORE_AVAILABLE_PATH/common/property-functions"
 set -eo pipefail
 [[ $DOKKU_TRACE ]] && set -x
 
+cmd-git-allow-host() {
+  declare desc="adds a host to known_hosts"
+  local cmd="git:allow-host"
+  [[ "$1" == "$cmd" ]] && shift 1
+  declare HOST="$1"
+  [[ -z "$HOST" ]] && dokku_log_fail "Please supply a git host"
+
+  ssh-keyscan -t rsa "$HOST" >> "$DOKKU_ROOT/.ssh/known_hosts"
+  dokku_log_info1 "$HOST added to known hosts"
+}
+
+cmd-git-clone() {
+  declare desc="creates an app from remote git repo"
+  local cmd="git:clone"
+  [[ "$1" == "$cmd" ]] && shift 1
+  declare APP="$1" GIT_REMOTE="$2" GIT_REF="$3" FLAG="$4"
+
+  ARGS=()
+  for arg in "$@"; do
+    if [[ "$arg" == "--build" ]]; then
+      FLAG="--build"
+      continue
+    fi
+
+    ARGS+=("$arg")
+  done
+
+  APP="$1"
+  GIT_REMOTE="$2"
+  GIT_REF="$3"
+
+  verify_app_name "$APP"
+
+  if [[ -z "$GIT_REMOTE" ]]; then
+    dokku_log_fail "Missing GIT_REMOTE parameter"
+    return
+  fi
+
+  fn-git-clone "$APP" "$GIT_REMOTE" "$GIT_REF"
+  if [[ "$FLAG" == "--build" ]]; then
+    if [[ -n "$GIT_REF" ]]; then
+      plugn trigger receive-app "$APP" "$GIT_REF"
+    else
+      plugn trigger receive-app "$APP"
+    fi
+  fi
+}
+
+cmd-git-fetch() {
+  declare desc="fetch the app at an optional repo object and build the codebase"
+  local cmd="git:fetch"
+  [[ "$1" == "$cmd" ]] && shift 1
+  declare APP="$1" GIT_REMOTE="$2" GIT_REF="$3" FLAG="$4"
+
+  ARGS=()
+  for arg in "$@"; do
+    if [[ "$arg" == "--build" ]]; then
+      FLAG="--build"
+      continue
+    fi
+
+    ARGS+=("$arg")
+  done
+
+  APP="$1"
+  GIT_REMOTE="$2"
+  GIT_REF="$3"
+
+  verify_app_name "$APP"
+
+  if [[ -z "$GIT_REMOTE" ]]; then
+    dokku_log_fail "Missing GIT_REMOTE parameter"
+    return
+  fi
+
+  fn-git-fetch "$APP" "$GIT_REMOTE" "$GIT_REF"
+  if [[ "$FLAG" == "--build" ]]; then
+    if [[ -n "$GIT_REF" ]]; then
+      plugn trigger receive-app "$APP" "$GIT_REF"
+    else
+      plugn trigger receive-app "$APP"
+    fi
+  fi
+}
+
+cmd-git-public-key() {
+  declare desc="outputs the dokku public deploy key"
+  local cmd="git:public-key"
+  [[ "$1" == "$cmd" ]] && shift 1
+
+  if [[ ! -f "$DOKKU_ROOT/.ssh/id_rsa.pub" ]]; then
+    dokku_log_fail "There is no deploy key"
+  fi
+  cat "$DOKKU_ROOT/.ssh/id_rsa.pub"
+}
+
 cmd-git-report() {
   declare desc="displays a git report for one or more apps"
   declare cmd="git:report"
@@ -69,6 +165,62 @@ cmd-git-report-single() {
     [[ "$match" == "true" ]] || dokku_log_fail "Invalid flag passed, valid flags:${valid_flags}"
     [[ "$value_exists" == "true" ]] || dokku_log_fail "not deployed"
   fi
+}
+
+fn-git-clone() {
+  declare desc="creates an app from remote git repo"
+  declare APP="$1" GIT_REMOTE="$2" GIT_REF="$2"
+  local APP_CLONE_ROOT="$PLUGIN_DATA_ROOT/$APP"
+  local APP_ROOT="$DOKKU_ROOT/$APP"
+  [[ -z "$APP" ]] && dokku_log_fail "Please specify an app to run the command on"
+
+  if [[ -d "$DOKKU_ROOT/$APP/refs" ]]; then
+    dokku_log_fail "The clone subcommand can only be executed for new applications"
+  fi
+
+  if [[ -d "$APP_CLONE_ROOT" ]]; then
+    dokku_log_fail "Clone in progress"
+  fi
+
+  if [[ -z "$GIT_REF" ]]; then
+    GIT_REF="$(fn-git-deploy-branch "$APP")"
+  fi
+
+  dokku_log_info1_quiet "Creating $APP from $GIT_REMOTE#$GIT_REF"
+  trap 'rm -rf $APP_CLONE_ROOT > /dev/null' RETURN INT TERM EXIT
+  git clone --depth 1 -n -qq --branch "$GIT_REF" "$GIT_REMOTE" "$APP_CLONE_ROOT"
+
+  if [[ "$GIT_REF" != "master" ]]; then
+    pushd "$APP" > /dev/null
+    git checkout -qq -b master
+    popd > /dev/null
+  fi
+
+  rsync -a "$APP_CLONE_ROOT/.git/" "$APP_ROOT"
+  fn-git-create-hook "$APP"
+}
+
+fn-git-fetch() {
+  declare APP="$1" GIT_REMOTE="$2" GIT_REF="$3"
+  local DOKKU_DEPLOY_BRANCH
+
+  DOKKU_DEPLOY_BRANCH="$(fn-git-deploy-branch "$APP")"
+  if ! git check-ref-format --branch "$DOKKU_DEPLOY_BRANCH" >/dev/null 2>&1; then
+    echo $'\e[1G\e[K'"-----> WARNING: Invalid branch name '$DOKKU_DEPLOY_BRANCH' specified via DOKKU_DEPLOY_BRANCH."
+    echo $'\e[1G\e[K'"-----> For more details, please see the man page for 'git-check-ref-format.'"
+    return
+  fi
+
+  pushd "$DOKKU_ROOT/$APP" > /dev/null
+  git remote rm remote > /dev/null 2>&1 || true
+  git remote add --mirror=fetch --no-tags remote "$GIT_REMOTE"
+  if [[ -z "$GIT_REF" ]]; then
+    git fetch remote "$DOKKU_DEPLOY_BRANCH"
+  else
+    git fetch remote
+    git update-ref refs/heads/master "$GIT_REF"
+  fi
+  popd > /dev/null
 }
 
 fn-git-last-updated-at() {
