Some refactoring of the ruby ps/config test

diff --git a/tests/apps/ruby-rack/check_deploy b/tests/apps/ruby-rack/check_deploy
--- a/tests/apps/ruby-rack/check_deploy
+++ b/tests/apps/ruby-rack/check_deploy
@@ -1,12 +1,19 @@
-#!/bin/bash
-set -e;
+#!/usr/bin/env bash
+set -eo pipefail
 URL="$1"; TARGET="$2"; APP="$3"; REPO="$4";
 
 function dokku(){
   echo | ssh dokku@$TARGET $@ || {
     code=$?
     echo "Failed on $@ with exit code $code"
-    exit 1
+    exit $code
+  }
+}
+function request(){
+  curl -s $@ || {
+    code=$?
+    echo "Failed on \`curl -s $@\` with exit code $code"
+    exit $code
   }
 }
 function abort(){
@@ -16,14 +23,13 @@ function abort(){
 
 # check http
 echo "-----> Testing $URL"
-output="$(curl -s $URL)"; test "$output" == "ruby/rack" || abort "failed test on: $output"
-echo "       ok"
+output=$(request $URL); test "$output" == "ruby/rack" || abort "failed test on: $output"
 
 # check config
 echo "-----> Testing dokku config $REPO"
 #dokku config $REPO true # TODO no config should not exit with 1
 #dokku config:get $REPO CONFTEST # TODO no config should not exit with 1
-output=$(curl -s $URL/env/CONFTEST); test "$output" == "n/a" || abort "failed test on: $output"
+output=$(request $URL/env/CONFTEST); test "$output" == "n/a" || abort "failed test on: $output"
 output=$(dokku config:set $REPO CONFTEST=1); test "$output" == "$(cat <<EOF
 -----> Creating /home/dokku/$REPO/ENV
 -----> Setting config vars and restarting $REPO
@@ -36,44 +42,61 @@ CONFTEST: 1
 -----> Deploy complete!
 EOF)" || abort "failed test on: $output"
 output=$(dokku config:get $REPO CONFTEST); test "$output" == "1" || abort "failed test on: $output"
-output=$(curl -s $URL/env/CONFTEST); test "$output" == "1" || abort "failed test on: $output"
+output=$(request $URL/env/CONFTEST); test "$output" == "1" || abort "failed test on: $output"
 output=$(dokku config $REPO); test "$output" == "$(cat <<EOF
 === $REPO Config Vars
 CONFTEST: 1
 EOF)" || abort "failed test on: $output"
-echo "       ok"
 
 # check ps
 echo "-----> Testing dokku ps $REPO"
-output=$(dokku ps $REPO);
+output="$(dokku ps $REPO)"
 # TODO how to test with wildcards?
 # echo "$output";
 # test "$output" == "$(cat <<EOF
 # === web: `bundle exec thin start -p $PORT worker`
 # web.1: Up 5 seconds
 # EOF)"
-output=$(curl -s $URL); test "$output" == "ruby/rack" || abort "failed curl test on: $output"
+output=$(request $URL); test "$output" == "ruby/rack" || abort "failed curl test on: $output"
 
 # scale up & see if still running
-output=$(dokku ps:scale $REPO web=2); echo "$output"; test "$output" == "$(cat <<EOF
+output=$(dokku ps:scale $REPO web=2); test "$output" == "$(cat <<EOF
 -----> Starting web
        2 processes up and running
-EOF)" || abort "failed dokku test on: $output"
+-----> Starting worker
+       0 processes up and running
+EOF)" || abort "failed 2 web test on: $output"
+output="$(request $URL)"; test "$output" == "ruby/rack" || abort "failed curl test on: $output"
 
-output="$(curl -s $URL)"; test "$output" == "ruby/rack" || abort "failed curl test on: $output"
+# verify that we get 2 different server id headers (assuming nginx uses round robin)
+s1=$(request -I $URL)
+s2=$(request -I $URL)
+test "$s1" != "$s2" || abort "failed round robin test: $s1 $s2"
 
 # scale back down & see if still running
 output=$(dokku ps:scale $REPO web=1); test "$output" == "$(cat <<EOF
 -----> Starting web
        1 processes up and running
-EOF)" || abort "failed test on: $output"
-output="$(curl -s $URL)"; test "$output" == "ruby/rack" || abort "failed test on: $output"
+-----> Starting worker
+       0 processes up and running
+EOF)" || abort "failed 1 web test on: $output"
+output="$(request $URL)"; test "$output" == "ruby/rack" || abort "failed test on: $output"
+
+# start a worker & see if still running
+output=$(dokku ps:scale $REPO worker=1); test "$output" == "$(cat <<EOF
+-----> Starting web
+       1 processes up and running
+-----> Starting worker
+       1 processes up and running
+EOF)" || abort "failed 1 worker test on: $output"
+output="$(request $URL)"; test "$output" == "ruby/rack" || abort "failed test on: $output"
 
 # scale to 0 & see that it's not running
-output=$(dokku ps:scale $REPO web=0); test "$output" == "$(cat <<EOF
+output=$(dokku ps:scale $REPO web=0 worker=0); test "$output" == "$(cat <<EOF
 -----> Starting web
        0 processes up and running
+-----> Starting worker
+       0 processes up and running
 EOF)" || abort "failed test on: $output"
-output="$(curl -s $URL)"; test "$output" != "ruby/rack" || abort "failed test on: $output"
-echo "       ok"
+output="$(request $URL)"; test "$output" != "ruby/rack" || abort "failed test on: $output"
 
