Add support for symlinked directory paths and sort the output

diff --git a/plugins/common/functions b/plugins/common/functions
--- a/plugins/common/functions
+++ b/plugins/common/functions
@@ -10,7 +10,7 @@ has_tty() {
 }
 
 dokku_apps() {
-  local INSTALLED_APPS=$(find $DOKKU_ROOT -maxdepth 1 -mindepth 1 -type d ! -name 'tls' ! -name '.*' -printf "%f\n") || (dokku_log_fail "You haven't deployed any applications yet")
+  local INSTALLED_APPS=$(find $DOKKU_ROOT -follow -maxdepth 1 -mindepth 1 -type d ! -name 'tls' ! -name '.*' -printf "%f\n" | sort) || (dokku_log_fail "You haven't deployed any applications yet")
   [[ $INSTALLED_APPS ]] && echo $INSTALLED_APPS
 }
 
